### ISSUE TITLE
Error when running notesRecognizer

### ISSUE THREAD

**Issue by pogihub** [mpralat/notesRecognizer#2]
Adjusting photo.
Preprocessing image.
Detecting lines.
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    main()
  File "main.py", line 24, in main
    staffs = get_staffs(adjusted_photo)
  File "D:\My Projects\GitHub\Download\notesRecognizer-master\notesRecognizer-master\getting_lines.py", line 120, in get_staffs
    all_lines, lines_image_color = detect_lines(hough, thresholded, 80)
  File "D:\My Projects\GitHub\Download\notesRecognizer-master\notesRecognizer-master\getting_lines.py", line 40, in detect_lines
    for result_arr in hough[:nlines]:
TypeError: 'NoneType' object is not subscriptable

**Comment by HeArchitect** [comment]
This means the input you give has no line that can be detected.
