### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by stexniolo** [mpralat/notesRecognizer#4]
Hello, i tried to run the program, but it showed me this error:
> python main.py -i input/real4.jpg
Adjusting photo.
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    main()
  File "main.py", line 23, in main
    adjusted_photo = adjust_photo(image)
  File "C:\Users\Stefano\Downloads\notesRecognizer-master\notesRecognizer-master\photo_adjuster.py", line 26, in adjust_photo
    _, contours, _ = cv2.findContours(edged, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)

How can i solve it? Thanks!

**Comment by LvnKoenigsegg** [comment]
Well, this comes a bit late, but it might help other people in the future.
Unfortunately, I can't explain where this error comes from. The only thing I know is that the function _cv2.findCountours(...)_ returns a tuple of 2 values. However, the code above tries to "unpack" those 2 values into three variables, which is impossible. To fix the error, just change the line __, contours, _ = cv2.findContours(edged, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)_ to __, contours = cv2.findContours(edged, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)_.
Hope it helps!
